### ISSUE TITLE
Reserved Memory

### ISSUE THREAD

**Issue by jaredwhitney** [jaredwhitney/os3#21]
Need to get a decent memory map on boot or in s2 and ensure that malloc marks all unusable blocks as already in use so they are not given out to programs.

**Comment by UnknownSilicon** [comment]
Can we have a gif of this breaking?

**Comment by jaredwhitney** [comment]
Nothing interesting really happens, it just crashes or red-screens at the
moment (probably starts executing some random part of memory instead of
actual code because of the way I have Components working atm).

**Comment by jaredwhitney** [comment]
Also it looks like it isn't even hitting any reserved memory unless either the allocation code or my math is really messed up... the only other option is that some other part of the code is writing a bunch of data to the memory assuming its free I guess, but pretty much everything should be using malloc instead of hardcoded addreses. Either I forgot about something that's hardcoded, window creation is using way more RAM than I thought, it IS actually hitting some reserved memory that just isn't reported by BIOS, or any of a number of values is being changed and causing a bunch of odd writes (malloc tables, image/Component sizes, buffer addresses, etx). The only thing is that the one time the bug actually did show something was when the address of the memory that was being affected overlapped with a text buffer, and it looked like at least one of the bytes was changing periodically on a timer, which is what makes me think that it might be some sort of memory-mapped hardware (plus, moving the memory allocation base to 2 times its normal starting value allows many more windows to be created before a similar crash occurs, so its definitely something related to memory). At worst if it can't be fixed or detected by normal means malloc can just perform a check to see if new sectors can be read and written with expected results before returning them for use (although if it is some hardware-mapped memory, manually probing it might cause even more problems...).

**Comment by jaredwhitney** [comment]
Resolved in b565eea176f23a9cb3fa85a5a47f9726d4dd24b5.
